Create garoon-plugin-uploader from internal project.
garoon/plugin-uploader pull request #1
Opened 2022-06-22 09:33 UTC by kk3939

2022-06-28 04:46 UTC, niwatonmaster commented on README.md
> +In the project of creating the plugin, type the following command.
どこでコマンドを実行してほしいかを明確にすると読みやすいはず
Type follow command to upload your plugin.
```
cd your-project

```

2022-07-08 07:24 UTC, niwatonmaster commented on src/utils.ts
> +  if (basicAuth) {
実行上の問題はないですが、後で読む人はBasicAuth未指定= nullであることを知らないので明確にしておくと良いと思います。
` if (basicAuth != null) { `

もしくは、ここまでの引数の渡し方を`BasicAuth | null `にするのをやめて、`BasicAuth.username`と`BasicAuth.password`でundefinedを許容し、ここで`if(basicAuth.username && basicAuth.password )`を確認するのも良いと思います。
basicAuthが引数に入ってなかった時の情報をどう渡すかの一貫性が保てればどちらでも良いと思います。

2022-07-08 08:06 UTC, niwatonmaster commented on src/utils.ts
> +const UPLOAD_WAIT_MILLISECOUNDS = 5000;
MILLISECOUNDS => MILLISECONDS

2022-07-08 08:26 UTC, niwatonmaster commented on src/utils.ts
> +
実行状況を知りたいので、ここと142行目でStart/End Uploading Fileを出力するとよさそうです。

2022-07-12 05:21 UTC, kk3939 commented on src/utils.ts
> +  if (basicAuth) {
検討の結果、nullか両方のプロペティが指定されているようにbasicAuthを宣言します。

2022-07-13 01:49 UTC, ueokande commented on .github/workflows/test.yml
> +      - uses: actions/checkout@v2
latest version is v3
https://github.com/actions/checkout

2022-07-13 01:50 UTC, ueokande commented on .github/workflows/test.yml
> +      - uses: actions/setup-node@v2
latest version is v3
https://github.com/actions/setup-node

2022-07-13 03:08 UTC, ueokande requested changes

2022-07-13 07:19 UTC, kk3939 commented on src/utils.ts
> +    throw new Error("Error: Target URL is invalid.");
I think you're right.
There are many cases that cause errors,  so I would like to change how to tell users that.

2022-07-13 07:24 UTC, kk3939 commented on src/utils.ts
> +    throw new Error("Error: Target URL is invalid.");
As can predict many reasons to cases error, I specify steps without catcing error and logging self-made eroor message.

```
console.log(`Open ${loginUrl}`);
await page.goto(loginUrl);
console.log("Trying to login.....");
```

2022-07-13 07:32 UTC, kk3939 commented on package.json
> +  "devDependencies": {
I forgot to add ones because the internal project is monorepo.

2022-07-13 09:09 UTC, kk3939 commented on .github/workflows/test.yml
> +      - main
Originally, I thought that it is easy to be over a limit of 20 plugins and troublesome to remove the added plugin when the upper limit is exceeded.
However, for me, it is better than the previous one in point of view of not contain bugs and code that behaves unintentionally.

Thank you. 
I 'll add a future branch to triggered branches.

2022-07-13 09:56 UTC, ueokande commented on src/utils.ts
> +    throw new Error("Error: Target URL is invalid.");
Your proposal is a well-known pattern in Node programs.  It is a good solution to identify the root cause of the errors and make it easier to report issues.  For your information, the following patterns are also commonly used:

- Wrap the error with a message:
  ```node
  try {
    ...
  } catch (e) {
    throw new Error(`Unable to login: ${e.message}`)
  }
  ```
- Output an root cause
  ```node
  try {
    ...
  } catch (e) {
    console.error(e)
    throw new Error('Unable to login');
  }
  ```

2022-07-15 08:48 UTC, kk3939 commented on src/utils.ts
> +    throw new Error("Error: Target URL is invalid.");
Thanks.
As "e" is inferred as unknown type in Typescript, can not access properties. 
Moreover, if wrap the error with e.mesage, we should set line feed code(\n).

For above reasons, I adopt the second method you have showed.

2022-07-15 09:14 UTC, ueokande commented on .github/workflows/test.yml
> +          yarn install --immutable
Sorry, `--immutable` is not support on yarn 1.x. Use `--frozen-lockfile` instead.

2022-07-19 06:04 UTC, merged