add license_finder
garoon/plugin-uploader pull request #9
Opened 2022-08-15 06:52 UTC by kk3939

2022-08-15 09:53 UTC, TomokoMiyake requested changes
ドキュメントと SD のプロジェクト設定見つつ CI 設定とファイル構成のレビューをしました。
判断ファイルの詳細は金子さんに確認してもらいましょう。

2022-08-15 09:53 UTC, TomokoMiyake commented on .github/workflows/license.yml
> +    runs-on: ubuntu-20.04
あえてバージョン指定しなくても良さそうです。
https://github.com/Cybozu-SD/cybozu-garoon-plugin/blob/develop/.github/workflows/check_license.yml

```suggestion
    runs-on: ubuntu-latest
```

2022-08-15 09:53 UTC, TomokoMiyake commented on .github/workflows/license.yml
> +  pull_request:
PR タイミング要りますか？

2022-08-15 09:53 UTC, TomokoMiyake commented on .github/workflows/license.yml
> +      - name: Install Node modules
実行速度改善のために、dependencies キャッシュしてあげると良さそうです。
ref:
https://github.com/Cybozu-SD/cybozu-garoon-plugin/blob/b45ecd9acc95df1716e1982f0294c80e8e68bcd4/.github/workflows/check_license.yml#L17-L27

https://github.com/kintone-labs/kintone-ui-component/blob/e855784f4aa0a6efca339d17adf5caca0793bcb2/.github/workflows/check_license_v1.yml#L27-L32

2022-08-15 09:53 UTC, TomokoMiyake commented on .github/workflows/license.yml
> +          license_finder --decisions-file=license_finder/doc/dependency_decisions.yml
実行用の license_finder/bin/license_finder を置いておく必要があると思います。
ref:
https://sharedoc.atlassian.net/wiki/spaces/OSSGuide/pages/1212743779/License+Finder#License-Finder%E3%81%AE%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E5%AE%9F%E8%A1%8C
https://github.com/cybozu-private/license-finder-examples/blob/main/bin/license_finder

2022-08-15 09:53 UTC, TomokoMiyake commented on license_finder/doc/use-with-redistribution-decisions.yml
> +---
ガイドに記載のスクリプトと違ったので、更新お願いします。
https://github.com/cybozu-private/license-finder-examples/blob/main/doc/use-with-redistribution-decisions.yml

再配布しない devDependencies 用にはこちらの判断ファイルを設置して、継承する必要があると思います。
https://github.com/cybozu-private/license-finder-examples/blob/main/doc/use-without-redistribution-decisions.yml

ということで、再配布するものとしないもので継承する判断ファイルが違ってくるので、dependency と devdependency と分けて GrPlugin のようなファイル構成にするのが良さそうだと思いました。
https://github.com/Cybozu-SD/cybozu-garoon-plugin/tree/develop/license_finder/doc

2022-08-17 08:21 UTC, kk3939 commented on license_finder/doc/use-with-redistribution-decisions.yml
> +---
> ガイドに記載のスクリプトと違ったので、更新お願いします。

コメント削除しただけなので、内容は一緒になります。

> ということで、再配布するものとしないもので継承する判断ファイルが違ってくるので、dependency と devdependency と分けて

ありがとうございます。
dependenciesとdevdependenciesで違う継承ファイルを読み込む方ようにします。

2022-08-17 08:23 UTC, kk3939 commented on .github/workflows/license.yml
> +          license_finder --decisions-file=license_finder/doc/dependency_decisions.yml
OSSなので、公開する上でいらないファイルはなるべく減らしたいです。CIで実行できれば十分なので、git監視下にローカル実行は入れないようにします。

2022-08-17 08:23 UTC, kk3939 commented on .github/workflows/license.yml
> +      - name: Install Node modules
承知しました。

2022-08-17 09:09 UTC, TomokoMiyake commented on .github/workflows/license.yml
> +  pull_request:
確かに事前検知するようにしておいても良さそうです。それで行きましょう。

2022-08-17 09:12 UTC, TomokoMiyake commented on .github/workflows/license.yml
> +          license_finder --decisions-file=license_finder/doc/dependency_decisions.yml
私の勘違いでした。license finder 自体は gem install してるからわざわざ実行ファイルをおいておく必要がないんですね。
CI で正しく実行できていれば、必要ないということでなしでokです。

2022-08-17 09:13 UTC, TomokoMiyake commented on license_finder/doc/use-with-redistribution-decisions.yml
> +---
コメント削除しただけだったのですね。了解です。それで良いかと思います。
dependencies と devdependencies 分ける対応もありがとうございます。

2022-08-17 10:19 UTC, TomokoMiyake approved these changes
LGTM!

2022-08-22 04:46 UTC, merged